Added Cerebrium for self-deployment
mistralai/platform-docs-public pull request #121
Opened 2024-08-08 17:46 UTC by milo157

2024-08-13 02:31 UTC, milo157 commented
@Bam4d Am I able to get a review on this please

2024-08-20 20:33 UTC, milo157 commented
@Bam4d @sublimator @sophiamyang Can I get a review on this please

2024-08-28 14:47 UTC, hrjn requested changes
Thanks for the review, there a few minor things that require edits but the rest is OK !

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +llm = LLM(model="mistralai/Mistral-7B-Instruct-v0.1", dtype="bfloat16", max_model_len=20000, gpu_memory_utilization=0.9)
Would it also work for `7B-Instruct-v0.3`? We should use the latest versions of our models in the examples.

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +You should then get the following response:
```suggestion
You should then get a message looking like this:
```

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +gpu = "AMPERE_A10"
Got an error saying "`hardware.gpu field is deprecated. Please use hardware.compute instead.`", is it related to this line ?

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +We need to add our Hugging Face token to our Cerebrium Secrets since using the Mistral model requires authentication. On first deploy, it will download the model and store it on disk therefore for su
Can you provide more details (or even just a doc link) on how to do this?

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +
This code does not work. Where is `item` defined ? I suppose you wanted to pass the function args but I'll let you confirm.

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +# Your huggingface token (HF_AUTH_TOKEN) should be stored in your project secrets on your Cerebrium dashboard
Please specify which permissions the HF token should have. I tried with a `READ` token and the resulting error message was making me believe that the token was either revoked or malformed (`{"run_id":"xxx","message":"Failed to initialize Cortex Application","error":"Invalid token passed!","traceback":"NoneType: None\n"}`). Switching to a `WRITE` token worked.

2024-08-28 14:47 UTC, hrjn commented on docs/deployment/self-deployment/cerebrium.mdx
> +
Can you add a consolidated version of `main.py` here? It's more practical for readers who want to copy-paste a single code block.

2024-08-28 15:09 UTC, hrjn approved these changes

2024-08-28 15:09 UTC, hrjn commented
LGTM, thanks !

2024-08-28 15:09 UTC, merged