Adding a third party Java client - LangChain4j
mistralai/platform-docs-public pull request #14
Opened 2024-01-31 15:58 UTC by czelabueno

Hi @sophiamyang a LangChain4j is an popular open-source java project and recently added Mistral AI client support.

2024-02-27 12:28 UTC, hrjn requested changes
Hi, thanks for the contribution 🙂 A few remarks:
* Slight wording change (see suggestion)
* Can you check that your code is compatible with the latest changes on La Plateforme ? You can see the changelog [here](https://docs.mistral.ai/platform/changelog/).

2024-02-27 12:28 UTC, hrjn commented on docs/platform/02-client.md
> +[langchain4j/lanchain4j-mistral-ai](https://github.com/langchain4j/langchain4j)
```suggestion
Mistral AI integration via [langchain4j](https://github.com/langchain4j/langchain4j)
```

2024-02-27 15:44 UTC, czelabueno commented
Hi @hrjn, I'm responsible for the Mistral AI integration for LangChain4j... changes are on the way 😊

2024-02-28 08:30 UTC, hrjn commented
>  Btw, for when you plan to update the public API specs? https://docs.mistral.ai/api/

Yes, we are looking into it !

2024-03-25 16:31 UTC, czelabueno commented
Hi @sophiamyang, langchain4j java client has been updated with last [changes](https://docs.mistral.ai/platform/changelog/) (function calling, new models and json format). You can check it [here](https://github.com/langchain4j/langchain4j/commit/ae68bf9ab31d3d38c1b1c9a45ca65bd91bd95415).
I hope that this help to Mistral users to integrate with their java apps.

Thanks!

2024-05-29 11:47 UTC, hrjn commented
Hello again! It seems that your PR was submitted before we conducted a large-scale refactoring of our documentation structure. To make sure that your link is included in the most current version, I've added it directly. This means that I'll be closing this PR, but rest assured that your client is now (or will be very soon) included in the list at https://docs.mistral.ai/getting-started/clients/#third-party-clients.

Thanks a lot for your contribution

2024-05-29 11:47 UTC, closed without merging

2024-05-30 00:06 UTC, czelabueno commented
Hi @hrjn , alright. Thanks!